build:
  maxIssues: 0

Compose:
  ComposableAnnotationNaming:
    active: true
  ComposableNaming:
    active: true
  ComposableParamOrder:
    active: true
  CompositionLocalAllowlist:
    active: true
  CompositionLocalNaming:
    active: true
  ContentEmitterReturningValues:
    active: true
  ContentTrailingLambda:
    active: true
  DefaultsVisibility:
    active: true
  LambdaParameterInRestartableEffect:
    active: true
  Material2:
    active: false
  ModifierComposed:
    active: true
  ModifierMissing:
    active: true
  ModifierNaming:
    active: true
  ModifierNotUsedAtRoot:
    active: true
  ModifierReused:
    active: true
  ModifierWithoutDefault:
    active: true
  MultipleEmitters:
    active: true
  MutableParams:
    active: true
  MutableStateAutoboxing:
    active: true
  MutableStateParam:
    active: true
  ParameterNaming:
    active: true
  PreviewAnnotationNaming:
    active: true
  PreviewNaming:
    active: false
  PreviewPublic:
    active: true
  RememberContentMissing:
    active: true
  RememberMissing:
    active: true
  UnstableCollections:
    active: false
  ViewModelForwarding:
    active: true
    allowedForwarding: StartExContent,MainNavigation
  ViewModelInjection:
    active: true

complexity:
  CyclomaticComplexMethod:
    threshold: 35
  ComplexCondition:
    threshold: 10
  LargeClass:
    threshold: 2200
  LongMethod:
    threshold: 300
  LongParameterList:
    functionThreshold: 13
    constructorThreshold: 12
  NestedBlockDepth:
    threshold: 8
  TooManyFunctions:
    thresholdInFiles: 60
    thresholdInClasses: 75
    thresholdInInterfaces: 20
    thresholdInObjects: 20
    thresholdInEnums: 20

naming:
  FunctionNaming:
    active: false

style:
  LoopWithTooManyJumpStatements:
    maxJumpCount: 3
  MagicNumber:
    active: false
  MaxLineLength:
    maxLineLength: 140
  ReturnCount:
    max: 15
    excludeGuardClauses: true
